version: '3'
services:
  nginx:
    build: web/nginx
    image: nginx-simple
    links:
      - "jenkins"
    #  - "opm_database"
    ports:
      - "80:80"
    volumes:
      - web_content:/var/www/
    depends_on:
      - hub_backend
      - opm_hub
      - monoserver
      - site
  
  site:
    build: web/site
    image: site_osweb
    ports:
      - "5000"
    environment:
      - OS_CONTENT_DIRECTORY
      - OS_DOWNLOAD_DIRECTORY
    volumes:
      - web_content:/var/www/
    depends_on:
      - opm_hub

  opm_hub:
    image: evilbeaver/os-hub:latest
    ports:
      - "5000"
    environment:
      - OSHUB_BINARY_ROOT=/var/www/hub.oscript.io
      - GITHUB_AUTH_TOKEN
    volumes:
      - web_content:/var/www/
    restart: always
  jenkins:
    build: jenkins
    image: osjenkins
    ports:
      - "8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - web_content:/var/www
volumes:
  web_content:
  jenkins_home: