version: '3'
services:
  nginx:
    build: web/nginx
    image: nginx-simple
    links:
      - "monoserver"
    ports:
      - "80:80"
    volumes:
      - web_content:/var/www/
  monoserver:
    build: web/site
    image: site_fcgi
    ports:
      - "9001:9001"
    volumes:
      - web_content:/var/www/
  
volumes:
  web_content: