version: '3'
services:
  nginx:
    build: web/nginx
    image: nginx-simple
    links:
      - "monoserver"
      - "jenkins"
      - "hub_backend"
      - "opm_database"
    ports:
      - "80:80"
    volumes:
      - web_content:/var/www/
    depends_on:
      - hub_backend
      - opm_database
      - monoserver
  monoserver:
    build: web/site
    image: site_fcgi
    ports:
      - "9001:9001"
    volumes:
      - web_content:/var/www/
  hub_backend:
    build: web/hub_backend
    image: hub-backend
    volumes:
      - web_content:/var/www/
  opm_database:
    build: web/opm_database
    image: opm-db
    command: -w db.json
    ports:
      - "3000:3000"
    restart: always
  jenkins:
    build: jenkins
    image: osjenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - web_content:/var/www
volumes:
  web_content:
  jenkins_home: