version: '3'
services:
  nginx:
    build: web/nginx
    image: nginx-simple
    links:
      - "monoserver"
      - "jenkins"
      - "hub_backend"
    #  - "opm_database"
    ports:
      - "80:80"
    volumes:
      - web_content:/var/www/
    depends_on:
      - hub_backend
      - opm_hub
      - monoserver
      - site
  
  monoserver:
    build: web/site-old
    image: site_fcgi
    ports:
      - "9001"
    volumes:
      - web_content:/var/www/
  
  site:
    build: web/site
    image: site_osweb
    ports:
      - "5000"
    environment:
      - OS_CONTENT_DIRECTORY=/var/www/oscript.io/App_Data
      - OS_DOWLOAD_DIRECTORY=/var/www/oscript.io/download
    volumes:
      - web_content:/var/www/

  hub_backend:
    build: web/hub_backend
    image: hub-backend
    environment:
      - PATH_TO_OSCRIPT_HUB
      - GITHUB_SUPER_TOKEN
      - GITTER_OAUTH_TOKEN
      - GITTER_ROOM
    ports:
      - "9002"
    volumes:
      - web_content:/var/www/
  
  opm_hub:
    image: evilbeaver/os-hub:latest
    ports:
      - "5000"
    environment:
      - OSHUB_BINARY_ROOT=/var/www/hub.oscript.io
      - GITHUB_AUTH_TOKEN
    volumes:
      - web_content:/var/www/
    restart: always
  jenkins:
    build: jenkins
    image: osjenkins
    ports:
      - "8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - web_content:/var/www
volumes:
  web_content:
  jenkins_home: